project:
  type: website
  output-dir: docs

website:
  title: "R Analytics: U.S. Drug Overdose Data"
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About"
      - href: ref.qmd
        text: "References"
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



